### ISSUE TITLE
Adding support of step values

### ISSUE THREAD

**Issue by christiankakesa** [kostya/cron_parser#1]
Coud be fine to support `"*/10 * * * *"` means at every 10th minute: [https://crontab.guru/#*/10_*_*_*_*](https://crontab.guru/#*/10_*_*_*_*)

**Comment by kostya** [comment]
it already should work, see spec: https://github.com/kostya/cron_parser/blob/master/spec/cron_parser_spec.cr#L33

**Comment by christiankakesa** [comment]
Sorry, I was mistaking with executor.
